-- =========================================================
-- #30  Payments: provider references + the two RPCs the Edge Functions use
--
-- Paystack is the first provider; the shape is provider-agnostic so Stripe
-- (#45) can be added without touching any of this SQL.
--
--   bookings/ride_requests.payment_provider, .payment_ref
--                       which provider holds the money and under what id
--   to_minor_units()    major → minor units (cents/kobo); mirrors the TS
--                       helper the Edge Functions use
--   start_payment()     called by create-checkout-session: verifies the caller
--                       owns the row and owes money, stores the reference and
--                       returns the amount **from the database**
--   mark_payment_paid() called by payment-webhook: finds the row by provider
--                       reference, checks the amount, flips payment_status
--
-- Both RPCs are service_role only. The Edge Functions verify the caller's JWT
-- and pass the resolved user id; nothing here is reachable from the browser.
-- =========================================================

-- ---------------------------------------------------------
-- 1. Provider reference columns
-- ---------------------------------------------------------
alter table public.bookings
  add column if not exists payment_provider text
    check (payment_provider is null or payment_provider in ('paystack', 'stripe')),
  add column if not exists payment_ref text;

alter table public.ride_requests
  add column if not exists payment_provider text
    check (payment_provider is null or payment_provider in ('paystack', 'stripe')),
  add column if not exists payment_ref text;

comment on column public.bookings.payment_ref is
  'Provider-side transaction reference for this booking. Generated by create-checkout-session and matched by payment-webhook; null until a checkout is started.';
comment on column public.ride_requests.payment_ref is
  'Provider-side transaction reference for this ride request. Generated by create-checkout-session and matched by payment-webhook; null until a checkout is started.';

-- One provider reference resolves to at most one row: the webhook must never
-- have to guess which booking a payment belongs to.
create unique index if not exists bookings_payment_ref_key
  on public.bookings(payment_provider, payment_ref)
  where payment_ref is not null;
create unique index if not exists ride_requests_payment_ref_key
  on public.ride_requests(payment_provider, payment_ref)
  where payment_ref is not null;

-- ---------------------------------------------------------
-- 2. Customers must not rewrite the reference either
--
-- The existing guards already stop a customer changing payment_status; a
-- customer who could point payment_ref at somebody else's paid transaction
-- would get the same result for free. Same triggers, two more columns.
-- ---------------------------------------------------------
create or replace function public.bookings_guard_customer_update()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  -- No JWT means service_role / a server-side job, not a customer.
  if auth.uid() is null then
    return new;
  end if;

  if public.has_role(auth.uid(), 'admin')
     or exists (
       select 1 from public.vehicles v
       where v.id = old.vehicle_id and v.operator_id = auth.uid()
     ) then
    return new;
  end if;

  if new.total_price      is distinct from old.total_price
  or new.price_breakdown  is distinct from old.price_breakdown
  or new.payment_status   is distinct from old.payment_status
  or new.payment_method   is distinct from old.payment_method
  or new.payment_provider is distinct from old.payment_provider
  or new.payment_ref      is distinct from old.payment_ref
  or new.vehicle_id       is distinct from old.vehicle_id
  or new.customer_id      is distinct from old.customer_id then
    raise exception
      'Customers cannot change pricing, payment, vehicle or ownership on a booking';
  end if;

  return new;
end;
$$;
revoke all on function public.bookings_guard_customer_update() from public, anon, authenticated;

create or replace function public.ride_requests_guard_customer_update()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  -- No JWT means service_role / a server-side job, not a customer.
  if auth.uid() is null then
    return new;
  end if;

  if public.has_role(auth.uid(), 'admin') or public.has_role(auth.uid(), 'operator') then
    return new;
  end if;

  if new.payment_status   is distinct from old.payment_status
  or new.payment_method   is distinct from old.payment_method
  or new.payment_provider is distinct from old.payment_provider
  or new.payment_ref      is distinct from old.payment_ref
  or new.customer_id      is distinct from old.customer_id
  or new.route_id         is distinct from old.route_id
  or new.passengers       is distinct from old.passengers then
    raise exception
      'Customers cannot change payment state, ownership, route or headcount on a ride request';
  end if;

  return new;
end;
$$;
revoke all on function public.ride_requests_guard_customer_update() from public, anon, authenticated;

-- ---------------------------------------------------------
-- 3. to_minor_units: what the provider actually charges
--
-- Providers take integers in the currency's smallest unit. Most currencies
-- have two decimals, a few have none (JPY, XOF, RWF — the last two matter,
-- Paystack settles in them) and a few have three.
-- ---------------------------------------------------------
create or replace function public.to_minor_units(_amount numeric, _currency text)
returns bigint
language sql
immutable
set search_path = public
as $$
  select round(
    coalesce(_amount, 0) * power(
      10,
      case upper(coalesce(_currency, 'ZAR'))
        when 'BIF' then 0 when 'CLP' then 0 when 'DJF' then 0 when 'GNF' then 0
        when 'JPY' then 0 when 'KMF' then 0 when 'KRW' then 0 when 'MGA' then 0
        when 'PYG' then 0 when 'RWF' then 0 when 'UGX' then 0 when 'VND' then 0
        when 'VUV' then 0 when 'XAF' then 0 when 'XOF' then 0 when 'XPF' then 0
        when 'BHD' then 3 when 'IQD' then 3 when 'JOD' then 3 when 'KWD' then 3
        when 'LYD' then 3 when 'OMR' then 3 when 'TND' then 3
        else 2
      end
    )::numeric
  )::bigint;
$$;
comment on function public.to_minor_units(numeric, text) is
  'Amount in the currency''s smallest unit (cents/kobo). Mirrors toMinorUnits() in supabase/functions/_shared/money.ts.';
revoke all on function public.to_minor_units(numeric, text) from public, anon, authenticated;
grant execute on function public.to_minor_units(numeric, text) to service_role;

-- ---------------------------------------------------------
-- 4. start_payment
--
-- The amount is never supplied by the caller: it is read from the row, so a
-- passenger cannot check out a R500 booking for R5.
-- ---------------------------------------------------------
create or replace function public.start_payment(
  _user_id uuid,
  _target_type text,
  _target_id uuid,
  _provider text,
  _reference text
)
returns table (
  target_type text,
  target_id uuid,
  amount numeric,
  currency text,
  customer_email text,
  customer_name text,
  description text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_booking public.bookings;
  v_request public.ride_requests;
  v_email text;
  v_name text;
begin
  if _user_id is null then
    raise exception 'Not authenticated' using errcode = '42501';
  end if;
  if _provider is null or _provider not in ('paystack', 'stripe') then
    raise exception 'Unknown payment provider: %', coalesce(_provider, '(null)');
  end if;
  if _reference is null or length(_reference) < 8 then
    raise exception 'A payment reference is required';
  end if;

  if _target_type = 'booking' then
    select * into v_booking from public.bookings where id = _target_id;
    -- Same error for "missing" and "not yours": never confirm a booking exists.
    if v_booking.id is null or v_booking.customer_id <> _user_id then
      raise exception 'Booking not found' using errcode = '42501';
    end if;
    if v_booking.payment_method <> 'prepay' then
      raise exception 'This booking is paid in cash on board';
    end if;
    if v_booking.payment_status = 'paid' then
      raise exception 'This booking is already paid';
    end if;
    if v_booking.payment_status <> 'pending' then
      raise exception 'This booking does not require payment';
    end if;
    if coalesce(v_booking.total_price, 0) <= 0 then
      raise exception 'This booking has no amount to pay';
    end if;

    update public.bookings
       set payment_provider = _provider, payment_ref = _reference
     where id = v_booking.id
     returning * into v_booking;

    select coalesce(nullif(v_booking.customer_email, ''), u.email),
           coalesce(nullif(v_booking.customer_name, ''), p.display_name, u.email)
      into v_email, v_name
      from auth.users u
      left join public.profiles p on p.id = u.id
     where u.id = v_booking.customer_id;

    return query select
      'booking'::text,
      v_booking.id,
      v_booking.total_price,
      v_booking.currency::text,
      v_email,
      v_name,
      format('ShuttleBook booking %s', left(v_booking.id::text, 8));

  elsif _target_type = 'ride_request' then
    select * into v_request from public.ride_requests where id = _target_id;
    if v_request.id is null or v_request.customer_id <> _user_id then
      raise exception 'Ride request not found' using errcode = '42501';
    end if;
    if v_request.payment_method <> 'prepay' then
      raise exception 'This ride is paid in cash on board';
    end if;
    if v_request.payment_status = 'paid' then
      raise exception 'This ride is already paid';
    end if;
    if v_request.payment_status <> 'pending' then
      raise exception 'This ride does not require payment';
    end if;
    if v_request.status = 'cancelled' then
      raise exception 'This ride was cancelled';
    end if;
    if coalesce(v_request.total_price, 0) <= 0 then
      raise exception 'This ride has no fare set; pay the driver on board';
    end if;

    update public.ride_requests
       set payment_provider = _provider, payment_ref = _reference
     where id = v_request.id
     returning * into v_request;

    select u.email, coalesce(p.display_name, u.email)
      into v_email, v_name
      from auth.users u
      left join public.profiles p on p.id = u.id
     where u.id = v_request.customer_id;

    return query select
      'ride_request'::text,
      v_request.id,
      v_request.total_price,
      v_request.currency::text,
      v_email,
      v_name,
      format('ShuttleBook ride %s → %s', v_request.origin_name, v_request.destination_name);

  else
    raise exception 'Unknown payment target: %', coalesce(_target_type, '(null)');
  end if;
end;
$$;
revoke all on function public.start_payment(uuid, text, uuid, text, text) from public, anon, authenticated;
grant execute on function public.start_payment(uuid, text, uuid, text, text) to service_role;

-- ---------------------------------------------------------
-- 5. mark_payment_paid
--
-- Idempotent: providers retry webhooks, and a replay must not be an error.
--
-- Found by reference, or — when a passenger finishes an abandoned checkout
-- after starting a newer one, so the row no longer carries that reference —
-- by the target the provider echoes back from the checkout metadata. Money
-- that arrived must always land somewhere.
-- ---------------------------------------------------------
create or replace function public.mark_payment_paid(
  _provider text,
  _reference text,
  _amount_minor bigint default null,
  _currency text default null,
  _target_type text default null,
  _target_id uuid default null
)
returns table (target_type text, target_id uuid, already_paid boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_type text;
  v_id uuid;
  v_status text;
  v_currency text;
  v_total numeric;
  v_due bigint;
begin
  if _provider is null or _reference is null then
    raise exception 'Provider and reference are required';
  end if;

  -- 1. the reference we stored when the checkout was created
  select 'booking', b.id, b.payment_status, b.currency::text, b.total_price
    into v_type, v_id, v_status, v_currency, v_total
    from public.bookings b
   where b.payment_provider = _provider and b.payment_ref = _reference;

  if v_id is null then
    select 'ride_request', r.id, r.payment_status, r.currency::text, r.total_price
      into v_type, v_id, v_status, v_currency, v_total
      from public.ride_requests r
     where r.payment_provider = _provider and r.payment_ref = _reference;
  end if;

  -- 2. the target carried on the transaction itself
  if v_id is null and _target_id is not null then
    if _target_type = 'booking' then
      select 'booking', b.id, b.payment_status, b.currency::text, b.total_price
        into v_type, v_id, v_status, v_currency, v_total
        from public.bookings b where b.id = _target_id;
    elsif _target_type = 'ride_request' then
      select 'ride_request', r.id, r.payment_status, r.currency::text, r.total_price
        into v_type, v_id, v_status, v_currency, v_total
        from public.ride_requests r where r.id = _target_id;
    end if;
  end if;

  if v_id is null then
    raise exception 'No booking or ride request matches % reference %', _provider, _reference;
  end if;

  if _currency is not null and upper(_currency) <> upper(v_currency) then
    raise exception 'Payment currency % does not match the % currency %',
      _currency, v_type, v_currency;
  end if;

  v_due := public.to_minor_units(v_total, v_currency);
  if _amount_minor is not null and _amount_minor < v_due then
    raise exception 'Payment of % is short of the % due on this %', _amount_minor, v_due, v_type;
  end if;

  if v_status = 'paid' then
    return query select v_type, v_id, true;
    return;
  end if;

  -- The reference that was actually paid replaces whatever is on the row.
  if v_type = 'booking' then
    update public.bookings
       set payment_status = 'paid', payment_provider = _provider, payment_ref = _reference
     where id = v_id;
  else
    update public.ride_requests
       set payment_status = 'paid', payment_provider = _provider, payment_ref = _reference
     where id = v_id;
  end if;

  return query select v_type, v_id, false;
end;
$$;
revoke all on function public.mark_payment_paid(text, text, bigint, text, text, uuid)
  from public, anon, authenticated;
grant execute on function public.mark_payment_paid(text, text, bigint, text, text, uuid) to service_role;
