-- Intentionally empty.
--
-- This file was a re-generated copy of 20260515120000_shuttle_routes_and_operator.sql
-- (vendor → operator rename, shuttle_routes, route_stops, ride_requests, RLS,
-- get_passenger_queue). Applying both on a fresh database fails on the second
-- pass (ALTER TYPE ... RENAME VALUE and CREATE TABLE are not idempotent), so the
-- May migration is the canonical one and this version is kept only so that
-- databases which already recorded 20260621184641 stay in sync with the history.
--
-- If `supabase db push` reports 20260515120000 as pending against a database
-- that already has these tables, mark it applied instead of running it:
--   supabase migration repair --status applied 20260515120000
SELECT 1;
