// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uigbnrqzfozqucbjarch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpZ2JucnF6Zm96cXVjYmphcmNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2Mzg1NzksImV4cCI6MjA2NzIxNDU3OX0.jk8tRHuC-jFhYaU67yOjRSe4sWP9we9aX1ix_S_0M98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});